### ISSUE TITLE
Deploy TODO

### ISSUE THREAD

**Issue by segiddins** [segiddins/rubygems-research#12]
- [x] install tailscale
- [x] create a user for segiddins
- [x] create a user for k3s
- [x] install k3s
- [x] get set up for persistent volume claims stored on disk(s)
- [x] install datadog cluster agent
- [x] add job to package docker image and upload to ghcr
- [x] write k8s yaml
- [x] deploy app!
